SELECT * FROM users_schema.users;
INSERT INTO users (first_name, last_name, email) VALUES ('Ahmed', 'Amine','Ahmed.amine@gmail.com');
INSERT INTO users (first_name, last_name, email) VALUES ('Jane', 'Smith', 'jane.smith@gmail.com');
INSERT INTO users (first_name, last_name, email) VALUES ('john', 'smith','alice.johnson@gmail.com');
SELECT * FROM users;
SELECT * FROM users WHERE email = 'Ahmed.amine@gmail.com';
SELECT * FROM users ORDER BY id DESC LIMIT 1;
UPDATE users SET last_name = 'Pancakes' WHERE id = 3;
DELETE FROM users WHERE id = 2;
SELECT * FROM users ORDER BY first_name;
SELECT * FROM users ORDER BY first_name DESC;